'magic-tavern-chunt-s-up-with-that-t-shirt-green': 9683093319
'magic-tavern-logo-t-shirt-yellow': 9683095751
'magic-tavern-logo-t-shirt-grey': 9683095111
'magic-tavern-shoes': 9891836231
'magic-tavern-usidore-shoes': 9891891911
'magic-tavern-usidore-t-shirt-black': 9683094151
